:internal:
= Install
:toc: left
:author: Jonny
:revnumber!: 1.0.0
:revdate: Tuesday, 09 February, 2021
:doctype:   article
:encoding:  utf-8
:lang:      en
:toc:       left
:toclevels: 10
:toc-title: Table of Content
:sectnums:
:last-update-label:
:nofooter!:
:media: print
:icons: font
:pagenums:
:imagesdir: images/
:numbered:
:toc: left
:xrefstyle: full


== Login to ubuntu user

   sudo su ubuntu

== Install openjdk-8-jdk

    sudo apt-get update

    sudo apt-get install openjdk-8-jdk

    sudo vim /etc/profile

    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
    PATH=$PATH:$HOME/bin:$JAVA_HOME/bin

== Install Docker

Refer to : https://docs.docker.com/engine/install/ubuntu/

=== Uninstall old versions if Exist

    sudo apt-get remove docker docker-engine docker.io containerd runc

=== Start Install Docker

- Update the apt package index and install packages to allow apt to use a repository over HTTPS:

    sudo apt-get update

    sudo apt-get install \
apt-transport-https \
ca-certificates \
curl \
gnupg-agent \
software-properties-common

- Add Docker’s official GPG key:

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- Verify that you now have the key with the fingerprint 9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88, by searching for the last 8 characters of the fingerprint.

    sudo apt-key fingerprint 0EBFCD88

- Use the following command to set up the stable repository

  sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

- INSTALL DOCKER ENGINE

  sudo apt-get update

  sudo apt-get install docker-ce docker-ce-cli containerd.io

  sudo docker -v

== Install JFrog as Container

- Create JFrog Home Directory

  sudo mkdir -p /opt/jfrog

  sudo vim /etc/profile

Add JFROG_HOME

  export JFROG_HOME=/opt/jfrog
  PATH=$PATH:$HOME/bin:$JFORG_HOME/

Save The profile and reload

  source /etc/profile

Create more dir

  mkdir -p $JFROG_HOME/artifactory/var/etc/
  cd $JFROG_HOME/artifactory/var/etc/
  touch ./system.yaml
  chown -R $UID:$GID $JFROG_HOME/artifactory/var
  chmod -R 777 $JFROG_HOME/artifactory/var

Run Docker with persistent volume to $JFROG_HOME/artifactory/var/

  docker run --name artifactory -v $JFROG_HOME/artifactory/var/:/var/opt/jfrog/artifactory -d -p 8081:8081 -p 8082:8082 releases-docker.jfrog.io/jfrog/artifactory-oss:latest

open browser http://SERVER_HOSTNAME:8082/ui/ or http://SERVER_HOSTNAME:8081/artifcatory

Default login :

  admin / password


== Run Nexus as Container

   sudo mkdir -p /usr/share/nexus/nexus_data

   sudo chmod 777 /usr/share/nexus/nexus_data

   sudo docker run -d -p 8081:8081 --name nexus -v /usr/share/nexus/nexus_data:/sonatypework sonatype/nexus

login admin / admin123

== Run Jenkins as Container

  sudo mkdir -p /var/jenkins_home

  sudo chmod -R 777 /var/jenkins_home

  sudo docker run --name jenkins -v jenkins_home:/var/jenkins_home -v jenkins_downloads:/var/jenkins_home/downloads -d -p 8090:8080 jenkins/jenkins:lts





